### ISSUE TITLE
init0.txt and init_x.txt are designed for what? They are quite different from the other three label files.

### ISSUE THREAD

**Issue by Zhangyong-Tang** [BUGPLEASEOUT/LasHeR#2]

**Comment by BUGPLEASEOUT** [comment]
Only init.txt, visible.txt and infrared.txt are the correct annotated files, and the rest should not be cared about.

**Comment by BUGPLEASEOUT** [comment]
Only init.txt, visible.txt and infrared.txt are the accurate annotation files, and the rest should not be cared about.
