### ISSUE TITLE
unzip error!

### ISSUE THREAD

**Issue by lingqing97** [BUGPLEASEOUT/LasHeR#3]
I downloaded the dataset from your BaiduNetdisk link, but I can't unzip the lasher.zip after cat the files together. The error as follows:
![image](https://user-images.githubusercontent.com/41864244/131090924-0cc7df91-e2de-4209-946a-69a576bec22c.png)

**Comment by LiShenglana** [comment]
> I downloaded the dataset from your BaiduNetdisk link, but I can't unzip the lasher.zip after cat the files together. The error as follows: ![image](https://user-images.githubusercontent.com/41864244/131090924-0cc7df91-e2de-4209-946a-69a576bec22c.png)

I met the same error, do you solve this problem? Hope for your reply, thank you!
