### ISSUE TITLE
There is no testing set, so the toolkit is for what?

### ISSUE THREAD

**Issue by Zhangyong-Tang** [BUGPLEASEOUT/LasHeR#6]

**Comment by BUGPLEASEOUT** [comment]
We adopt two evaluation protocols for the evaluation of tracking algorithms. First, we use the entire dataset as a testing set. Then we split LasHeR into a training subset and a testing subset. Please refer to the file named List_for_Protocol2 for the sequences of two sunsets.

**Comment by Zhangyong-Tang** [comment]
Thanks, i have find the protocol2.
