### ISSUE TITLE
Where is Unaligned LasHeR?

### ISSUE THREAD

**Issue by easycodesniper-afk** [BUGPLEASEOUT/LasHeR#8]
Great work! I noticed that your paper says that you've released an unaligned version of LasHeR?But I found anno files named init.txt/visible.txt/infrared.txt are completely identical.

**Comment by BUGPLEASEOUT** [comment]
Yes, the current LasHeR uploaded is aligned. We are sorting out the unregistered datasets and doing some filtering based on LasHeR's data. After that, we will upload them. Please wait……

**Comment by easycodesniper-afk** [comment]
> Yes, the current LasHeR uploaded is aligned. We are sorting out the unregistered datasets and doing some filtering based on LasHeR's data. After that, we will upload them. Please wait……

Aha, what a pity. Do you have a specific schedule about that now? Looking forward for your work!
