### ISSUE TITLE
Can you provide the aligned version?

### ISSUE THREAD

**Issue by jiwei0921** [BUGPLEASEOUT/LasHeR#9]
Thanks for your great job! Are you planning to provide the aligned LasHeR?

**Comment by BUGPLEASEOUT** [comment]
Aligned and unaligned version of LasHeR were uploaded.  Please check.

**Comment by laisimiao** [comment]
@BUGPLEASEOUT 
What's the difference between aligned and unaligned version? Are images the same? Before unzip, I think unaligned version just provide the difference gt label but aligned is same label?
